# Generated by Django 4.0.4 on 2022-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Book_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
